### ISSUE TITLE
New Module: domReady

### ISSUE THREAD

**Issue by aterranova-bv** [bazaarvoice/bv-ui-core#29]
# Summary
I'd like to port the [domReady](https://github.com/bazaarvoice/scoutfile/blob/master/lib/browser/domReady.js) module from [Scoutfile](https://github.com/bazaarvoice/scoutfile) here to bv-ui-core.

# Explanation
As of version 1.7.0, Scoutfile includes bv-ui-core as a dependency.  We've ported most everything else over on an as-needed basis and domReady now fits that bill.

Projects using Scoutfile should be unaffected and projects using bv-ui-core and not Scoutfile gain access to this functionality.

# Proposed Work
  1. Add `domReady` module to `bv-ui-core`
  2. Update `Scoutfile` to use `bv-ui-core`'s version of `domReady` instead of its own `domready` dependency

# Alternatives
Since this module just exposes the [domready NPM module](https://www.npmjs.com/package/domready), projects using bv-ui-core and not Scoutfile could add that module as an additional dependency and go on their way. 

Since we moved most everything else over though, I am proposing we stick with the pattern.

**Comment by brianarn** [comment]
Given that it's literally just a wrap around the use of the `domready` npm module, I'd be more inclined to suggest that we have some sort of guidelines/recommendation somewhere around what modules we need.

That doesn't necessarily feel like a good fit for this repo, though, so much as some internal documentation.

**Comment by rmurphey** [comment]
What probably makes more sense is a scoutfile major version bump that drops the domReady module from scoutfile -- given that, as you point out, it's just a wrapper for an npm module. I'm also :-1: on adding that wrapper here, though.

**Comment by aterranova-bv** [comment]
Okay cool, thanks!
