### ISSUE TITLE
Logging solution

### ISSUE THREAD

**Issue by sirugh** [bazaarvoice/bv-ui-core#30]
It seems like we don't have a recommended logging module for front-end apps.

console.log is discouraged, but it would be convenient to have a module here that wrapped that behavior safely.

**Comment by rmurphey** [comment]
Things I would want from this:

- behaves a whole lot like console.log
- silent in production
- can be enabled in production by setting a cookie

**Comment by sirugh** [comment]
Suggestion by @benhollander: https://github.com/pimterry/loglevel

**Comment by brianarn** [comment]
Seems like loglevel supports the desired goals of the project, aside from the production enabling via cookie. We have other code around BV that supports this pattern, and at a cursory glance, it looks like loglevel would support a plugin wherein we could introduce that behavior.

That being said, we do also have a more comprehensive logging solution in another project, which already supports all of the above criteria, along with deeper support for `console` similarness. It appears that loglevel doesn't support things like `group`, `time`, or `assert`.

It does support the idea of unique loggers, whereas our internal version is a single instance for everyone, which could be interesting (though I'm not sure how much value that would bring in practice).

**Comment by rmurphey** [comment]
Any further thoughts on this? What do we want logging to look like? I'd love to see a shared logging solution here.

**Comment by sirugh** [comment]
loglevel sounds fine if we can write a plugin to wrap its usage.

**Comment by benhollander** [comment]
>That being said, we do also have a more comprehensive logging solution in another project, 

What's that?

**Comment by sirugh** [comment]
I believe he is referring to BVReporter: https://github.com/bazaarvoice/firebird/blob/master/static/dev/scripts/framework/util/bvreporter.js

**Comment by benhollander** [comment]
If that's already vetted and something that we already like, I'm :+1: for using it more.

**Comment by brianarn** [comment]
Given that BVReporter has been pretty vetted and meets all of @rmurphey's asks above, we could easily abstract it out for use in the repo. That was the piece of code I was referring to.

**Comment by sirugh** [comment]
https://github.com/bazaarvoice/bv-ui-core/compare/bazaarvoice:master...sirugh:logger?expand=1
