### ISSUE TITLE
Proposed: require/define module for sharing dependencies across files

### ISSUE THREAD

**Issue by rmurphey** [bazaarvoice/bv-ui-core#33]
As I'm thinking about HTTP/2, I'm realizing that there will be broader applications for the ability to share dependencies across files: as we break large applications up into smaller files, those smaller files will likely have common dependencies (e.g. lodash). We'll need a way to load a dependency once, and share it across files. 

The bazaarvoice/static-asset-service repo already does this for a very specific set of assets. I'd like to extract the require/define functionality of that repo to this one, and then have the static asset service repo consume the functionality provided here. A consumer of this new module might look like this:

```js
var VERSION = '1.0.0';
var deps = require('bv-ui-core/dependencyManager');

var hosts = {
  // ...
};

module.exports = function (config) {
  var env = config.env || 'prod';
  var baseURL = config.baseUrl || ('https://' +
    (hosts[env] || hosts.prod) +
    '/common/static-assets/' +
    VERSION + '/');

  return deps({
    loader : config.loader,
    namespace : config.namespace
    makeURLs : function (assets) {
      return baseURL + encodeURIComponent(requests.sort().join('+')) + '.js'
    }
  });
};
```

A consumer module would be able to specify where and how to load assets; the bv-ui-core module would provide `require` and `define` and handle the bookkeeping: making sure that required assets had a way to define themselves, and that required assets would be resolved immediately if already defined.

**Comment by brianarn** [comment]
Alongside this, would there be any development on making static assets into more of a dynamic service that builds and serves the requested combinations on the fly (caching them once requested)?

A small part of me feels like it's re-inventing a lightweight form of AMD, and I wonder if there'd be any way to leverage some pre-existing module loading solutions for this purpose, though that might prove to be more painful/problematic than just building our own.

**Comment by rmurphey** [comment]
I'd consider that effort valuable, reasonably straightforward, and separate. 

This is definitely creating a very lightweight variation on AMD, and I'm OK with that given that this code needs to ship in the scout. That said, I'd be open to a PR that proposed a way to use an existing module.
