### ISSUE TITLE
How to default logging to Logger.OFF?

### ISSUE THREAD

**Issue by rmurphey** [bazaarvoice/bv-ui-core#49]
My reading of the logger module is that it starts with a log level of 1, and then resets the log level to whatever is found in the _bvui_debug cookie, if anything. 

For production, I want to start the logger with a default log level of 4 (OFF), but then defer to whatever is found in the _bvui_debug cookie. I don't see a way to do this with the current module: it seems that the default log level always starts at 1 (INFO). If my application sets a log level, it will override anything that was set in the cookie, making the cookie not very useful.

I'd propose that:

- The module start at a default level of OFF
- The `setLogLevel` method be changed:

```js
setLogLevel: function (level, force) {
  logLevel = (!cookieObj.logLevel || force) ? 
    (level || Logger.LOG) : 
    cookieObj.logLevel;
  logger('log', [ 'Log level set to', logLevel ]);
}
```

This way, applications can set a log level, but the setting will defer to the level in the cookie, unless the `force` argument is true.

**Comment by rmurphey** [comment]
cc @sirugh

**Comment by sirugh** [comment]
So we want the cookie to take precedence over the application? I thought it was the other way around.

And you are correct, it always starts at 1 unless the debug cookie is found.

**Comment by sirugh** [comment]
Oh I see now. Yea this makes a lot of sense. Maybe @nason could throw this in with his PR to fix group?

**Comment by rmurphey** [comment]
Let's handle this in a separate PR.

**Comment by sirugh** [comment]
#50
