### ISSUE TITLE
Prevent style sheets from loading twice

### ISSUE THREAD

**Issue by bv-jason-dippel** [bazaarvoice/bv-ui-core#52]
There exists an issue where certain work has lead to situations where a single CSS file is being requested multiple times. This creates unnecessary load delays.

I propose we add a new module to bv-ui-core that provides the ability to check whether or not the CSS is already loaded and, if not, load a file from a given URL (if it's already present, just return). Ideally, we would have something that could be used as the following:

```js
import cssLoadChecker from 'bv-ui-core/lib/cssLoadChecker'

cssLoadChecker.checkAndLoadStyleSheet(namespace.cssUrl)
      .then( () => {
        // do something on success
      })
      .catch( (error) => {
        throw new Error('Error loading css: ' + error)
      })
```

Where `cssLoadChecker.checkAndLoadStyleSheet(namespace.cssUrl)` returns a promise that will be fulfilled upon loading/verifying the CSS file. 

Verifying will be done by checking for the existence of a certain style (ie display: none) on an empty div that we add with class `bv-verify-css-loaded` (or could possibly take in the class to look for as a param).

Something like this already exists within Firebird and is useful in the work I'm currently doing, and most likely future work as well. I believe this to be a good reason to add it to the bv-ui-core repo.

**Comment by sirugh** [comment]
We would need to make sure that the case used to validate the css would work for any consumers. That may mean having a classname be passed as an option as well.

**Comment by bv-jason-dippel** [comment]
Taking in the class name to look for is no problem. Determining what styles to look for as a means of knowing the CSS has loaded is a little more interesting imo. I don't think it's reasonable to take the styles in as a param as I believe it will unnecessarily complicate the code, but I'm curious as to what others think.

**Comment by benhollander** [comment]
I haven't looked at the static asset service much - could it be used for this?

**Comment by sirugh** [comment]
@benhollander AFAIK the SAS is used for loading less dynamic assets such as jQuery at a specific version, or constants that aren't going to change.

That being said and though client css is generated at build time, we may be able to modify the SAS to read from a bucket and direct requests for css files to the appropriate locations. Currently we just store the jquery/backbone/lodash code in the SAS repo. It would have to read from an external store to handle the css.

**Comment by aterranova-bv** [comment]
> a single CSS file is being requested multiple times

Won't the browser cache the requested CSS file?

Or are we trying to solve multiple requests going out before the first one has returned?

**Comment by bv-jason-dippel** [comment]
The browser would cache it so the second request would get the file faster, but it would still be parsed by the browser and then applied to the DOM tree which takes time.

I would love to be able to prevent multiple requests going out to the same file before one has returned but I'm not sure that's possible. I don't want to assume I'm guaranteed to know the URL for the initial request (doesn't get added to something like document.styleSheets until it's been received).

**Comment by rmurphey** [comment]
I'd definitely encourage looking into leveraging the static asset service
for this, even though it would require modification. I also opened an issue
suggesting that the SAS itself is a candidate for bv-ui-core.

**Comment by reason-bv** [comment]
@rmurphey I'm currently half-way into putting the SAS client into bv-ui-core. Started last week. Unfortunately I discovered it doesn't really work as written - only if everything happens in the right order, and has some failure modes in which requests never get callbacks due to the way in which people make them, ordering, dependencies, etc. So some adjustment is needed; I'll be getting there, as work on other things allows.

**Comment by taylormck** [comment]
Our styles need to be customized to various configurations when we build. If SAS could be modified to look up an arbitrary URL and share it across applications, it could work, but as-is, I don't believe it solves the challenge we're facing.

**Comment by bv-jason-dippel** [comment]
I've been working on adding this to the repo but recently noticed that there's no library included in package.json that supports the use of promises. I'm supporting that we add 'q' to the list of dependencies so that we can use promises.

I'm currently running into an issue where a callback could be called in multiple places, but only the first call would be valid. Using promises would easily and efficiently resolve this issue.

**Comment by tnunamak** [comment]
Instead of Q, what about [core-js](https://github.com/zloirock/core-js/blob/master/es6/promise.js) for better forward-compatibility?

**Comment by reason-bv** [comment]
@bv-jason-dippel bv-ui-core is very deliberately ultra-minimal with respect to what it pulls in. There are no dependencies, and that is by design. I'd rather it didn't add a promise library - that should be the responsibility of people using bv-ui-core.

**Comment by rmurphey** [comment]
Adding to what @reason-bv said: promises are ultimately just (very tasty) sugar around the node-style callback pattern. The promise interface is definitely nice, but you can support success/error handling using node-style callbacks, e.g. `function (err, result) { ... }`.
