### ISSUE TITLE
Don't use fetch

### ISSUE THREAD

**Issue by sirugh** [bazaarvoice/bv-ui-core#65]
We need a better fetch polyfill. Something that does safer checks for the native `window.fetch`.

**Comment by supernova-at** [comment]
Specifically we don't want to trust custom client polyfills of `window.fetch`, as they have come back to bite us in the past.

**Comment by aterranova-bv** [comment]
Specifically we don't want to trust custom client polyfills of window.fetch, as they have come back to bite us in the past.

**Comment by sirugh** [comment]
On second thought, it's probably OK that we just use `fetch` so long as we call it out in the docs for the module that uses it. That way the users of bv-ui-core can choose how to polyfill. We definitely should not force a polyfill in this repo.

**Comment by Velveeta** [comment]
Why not simply force a when the native version isn't available, and only in local context? Remember that the whatwg-fetch polyfill just attaches its fetch definition to whatever it receives as 'self', which it injects based on this check with it executes its IIFE: (typeof self !== 'undefined' ? self : this)... That means you should be able to do this:

const oldSelf = global.self;
const namespace = global.self = {};
require('whatwg-fetch');
global.self = oldSelf;
namespace.fetch(url).then(whatever);

...without any pollution of anything outside of this module, and be guaranteed a spec-compliant version of fetch is executed...

**Comment by reason-bv** [comment]
I think the plot here is that we really don't want to add any extra weight at all to bv-ui-core if we can possibly avoid it.

**Comment by Velveeta** [comment]
Ok that makes sense.
